services:
  import-service:
    env_file:
      - ./app/.env
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: import-service
    # depends_on:
    #   - clickhouse
    command: ["sh"]
    stdin_open: true   # эквивалент -i
    tty: true          # эквивалент -t
    volumes:
      # CSV файлы
      - ${BIND_VOLUMES}/rag_csv:/app/data
      - ${BIND_VOLUMES}/distill/models:/app/models
      - ${BIND_VOLUMES}/distill/cache:/app/cache
    environment:
      CH_HOST: ${CH_HOST}
      CH_PORT: ${CH_PORT}
      CH_USER: ${CH_USER}
      CH_PASSWORD: ${CH_PASSWORD}
    # Не запускаем автоматически, только по команде
    restart: "no"
    networks:
      - clickhouse_network

networks:
  clickhouse_network:
    name: clickhouse_network
    driver: bridge
    external: true
