services:
  import-service:
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: import-service
    # depends_on:
    #   - clickhouse
    # три команды ниже для простого входа в контейнер
    # command: ["sh"]
    # stdin_open: true   # эквивалент -i
    # tty: true          # эквивалент -t
    volumes:
      # CSV файлы
      - ${BIND_VOLUMES}/rag_csv:/app/data
      - ${BIND_VOLUMES}/distill/models:/app/models
      - ${BIND_VOLUMES}/distill/cache:/app/cache
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      NVIDIA_DISABLE_REQUIRE: true
      CH_HOST: ${CH_HOST}
      CH_PORT: ${CH_PORT}
      CH_USER: ${CH_USER}
      CH_PASSWORD: ${CH_PASSWORD}
    # Не запускаем автоматически, только по команде
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - clickhouse_network

networks:
  clickhouse_network:
    name: clickhouse_network
    driver: bridge
    external: true
